# fly.toml app configuration file generated for debconf24-bof-v2 on 2024-07-28T16:16:35+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'debconf24-bof-v2'
primary_region = 'nrt'

[env]
  UPSTASH_REDIS_REST_URL='https://probable-beetle-55626.upstash.io'
  UPSTASH_REDIS_REST_TOKEN='AdlKAAIjcDE2NWRjZmM1N2U1N2Y0OTg3ODc0NjA1MDJhMjVjMGViZXAxMA'
  DEBIAN_SALSA_CLIENT_ID='ed490af944e8abf158ef9a2d18cef86febfd7abac0ade5af7d0e53716bd96132'
  DEBIAN_SALSA_CLIENT_SECRET='gloas-4bb27db0510535b0274c996a0043e28ee866ca4df0c85a189cf3b3a3cc2b83ba'
  AUTH_TRUST=true
  AUTH_SECRET='275a5d8b42b26f5e68bc089da25ed6ae'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-2x'
